### PR TITLE
Feature/react app

### PR DESCRIPTION
**Pull request by joshuaoivie**
Dear code reviewer,

This pull request contains my commits for my React Capstone project. In this pull request, I introduced the following:

- Add Linter
- Setup React
- Setup Redux
- Create UI Components
- Fix Linter Errors
- Add README
- Host Project

Here:s my video link as well: https://www.loom.com/share/99d1786221d948ebbffa14d150440b4c

Warm Regards,
Joshua Ivie.

### CODE REVIEW

**Review by andersonlebon — CHANGES_REQUESTED** [review]
## Hi @joshuaivie 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

almost-there
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [x] Kindly check comments under the review.

https://www.loom.com/share/9d6ad108b0d24a169d449b8858e55214

- [x] KIndly would you please provide a video presentation with sound. This one is muetted.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by joshuaoivie** [comment]
Hello Code Reviewer,

Thank you for your kind review. Kindly see the updated video link with audio: https://www.loom.com/share/99d1786221d948ebbffa14d150440b4c

Warm Regards,
Joshua Ivie.

**Review by andersonlebon — APPROVED** [review]
## Hi @joshuaivie 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

nodding-yes

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by joshuaoivie** [comment]
Thank you @andersonlebon

**Pull request merged**
